
server:
  port: 10001
spring:
  application:
    name: niit-rick-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

    gateway:
      routes: # 网关路由配置
        - id: niit-rick-auth # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://niit-rick-auth # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/auth/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        - id: niit-rick-xtimer # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://niit-rick-xtimer
          predicates:
            - Path=/xtimer/**
          filters:
            - RewritePath=/xtimer/(?<segment>.*), /$\{segment}
        - id: niit-rick-seckill # 路由id，自定义，只要唯一即可
          uri: lb://niit-rick-seckill # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/sec_kill/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        - id: niit-rick-testconsumer
          uri: lb://niit-rick-demo
          predicates:
            - Path=/demo/**
          filters:
            - AuthenticationFilter
        - id: niit-rick-lottery # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://niit-rick-lottery
          predicates:
            - Path=/lottery/**
          filters:
            - AuthenticationFilter
        - id: niit-rick-admin # 路由id，自定义，只要唯一即可
          uri: lb://niit-rick-admin
          predicates:
            - Path=/admin/**
         # filters:
         #   - AuthenticationFilter




